### ISSUE TITLE
Shadowing *claylib-background* doesn't work

### ISSUE THREAD

**Issue by mjkalyan** [defun-games/claylib#28]
As observed in this thread https://github.com/defun-games/claylib/pull/26#discussion_r936074703

It appears that shadowing `*claylib-background*` for use with `with-drawing` doesn't work. The background is always drawn as the initial global value of `*claylib-background*` (`+raywhite+`).

**Comment by shelvick** [comment]
The problem is simple, I just haven't decided how to fix it yet.

The `with-drawing` macro is defined in `claylib/ll` to use `*claylib-background*` -- also defined in `claylib/ll`. The variable you're trying to shadow is the one from `claylib`. Problem is, everything in `claylib` expects a `rl-color` while everything in `claylib/ll` expects a C `Color` so it's not as simple as just using the ll version of `*claylib-background*`.
