### ISSUE TITLE
UNBOUND-SLOT when freeing triangle objects

### ISSUE THREAD

**Issue by mjkalyan** [defun-games/claylib#6]
Because triangles don't set their `%position` slot inherited from `game-object`, when `free` tries to clean up the slot we get an error. One working solution to this is just giving `%position` an `:initform` like `(make-vector2 0 0)`. Any thoughts @shelvick?

**Comment by shelvick** [comment]
Aha. So I made an assumption in `2d-object` that every 2D object would indeed have a position -- that assumption was broken with triangles and now needs to be reworked.

I am trying to move away from `:initform` and the like and doing lazy assignment of default values via `default-slot-value` wherever possible. That said, we don't actually want a default value for `%position`. Assigning a default for that could violate user expectations and lead to confusion instead of simply telling them "Hey, you forgot to give this thing a position."

I think we just want to push `%position` out to the child objects that need it instead of leaving it in `2d-object`.

**Comment by mjkalyan** [comment]
> push %position out to the child objects that need it

Sounds good! That'll be in my next PR.

**Comment by mjkalyan** [comment]
In this case, is there any reason for `game-object` to exist?

```lisp
(defclass game-object ()
  ((%position :initarg :pos
              :accessor pos)))

**Comment by shelvick** [comment]
Be careful, there could be a number of assumptions elsewhere in the code of `%position` being a slot in `game-object`. If you run into trouble I can deep dive on this tonight. A simpler _short-term_ fix would be to just modify the `free` method to make sure `%position` is bound before trying to free it.

**Comment by mjkalyan** [comment]
Okay, I'll have a better look at it tomorrow. I'm logging off for the night, so if you want to dive into it be my guest - I'll check for updates, if any, in the morning.

**Comment by shelvick** [comment]
I went for the quick fix. The shape/object hierarchy is suboptimal in some ways, but that problem can wait for another day.
